imports:
    - { resource: parameters.yml }

services:
    roots.discordnotifications.notification_service:
        class: lmg\lmgnotifications\notification_service
        arguments:
            - '@config'
            - '@dbal.conn'

    roots.discordnotifications.listener:
        class: lmg\lmgnotifications\event\notification_event_listener
        arguments:
            - '@language'
            - '@lmg.lmgnotifications.notification_service'
        tags:
            - { name: event.listener }
